FROM wurstmeister/kafka:2.12-2.4.1

COPY ./java/java-spiffe-provider-0.6.3-all-linux-x86_64.jar /usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/
COPY ./java/java.security /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/