print('Hello Tiltfile')

allow_k8s_contexts('k3d-k3s-default')
default_registry('k3d-myregistry.localhost:5000')

k8s_yaml(['spire-server/spire-namespace.yaml',
    'spire-server/server-account.yaml',
    'spire-server/server-cluster-role.yaml',
    'spire-server/server-configmap.yaml',
    'spire-server/server-service.yaml',
    'spire-server/server-statefulset.yaml',
    'spire-server/spire-bundle-configmap.yaml'])

k8s_yaml([
    'spire-agent/agent-account.yaml',
    'spire-agent/agent-cluster-role.yaml',
    'spire-agent/agent-configmap.yaml',
    'spire-agent/agent-daemonset.yaml'
])

custom_build(
  'java-kafka-ssl-factory',
  'scripts/build_docker.sh $EXPECTED_REF',
  ['./java-kafka-ssl-factory'],
  skips_local_docker=True,disable_push=True
)
k8s_yaml(['app/client-deployment.yaml'])

# Kafka installation
custom_build(
  'custom-cp-enterprise-kafka',
  'custom-cp-enterprise-kafka/build_docker.sh $EXPECTED_REF',
  ['./custom-cp-enterprise-kafka'],
  skips_local_docker=True,disable_push=True
)

k8s_yaml(local('helm template kafka cp-helm-charts -f cp-helm-charts-k3d/values.yaml'))
watch_file('cp-helm-charts-k3d')

local_resource('attestation', cmd='spire-agent/attestation.sh')
local_resource('integration tests', cmd='scripts/2_run_test.sh')

