
allow_k8s_contexts('k3d-k3s-default')
default_registry('k3d-myregistry.localhost:5000')

k8s_yaml(['spire-server/spire-namespace.yaml',
    'spire-server/server-account.yaml',
    'spire-server/server-cluster-role.yaml',
    'spire-server/server-configmap.yaml',
    'spire-server/server-service.yaml',
    'spire-server/server-statefulset.yaml',
    'spire-server/spire-bundle-configmap.yaml'])

k8s_yaml([
    'spire-agent/agent-account.yaml',
    'spire-agent/agent-cluster-role.yaml',
    'spire-agent/agent-configmap.yaml',
    'spire-agent/agent-daemonset.yaml'
])
k8s_resource('spire-agent', resource_deps=['spire-server'])

# Strimzi Kafka installation
k8s_yaml(['strimzi-kafka/strimzi-admin.yaml','strimzi-kafka/kafka-ephemeral-single.yaml'])
k8s_yaml(kustomize('strimzi-kafka'))
k8s_resource('strimzi-cluster-operator')
k8s_resource('kafka-client-shell', resource_deps=['strimzi-cluster-operator'])


load('ext://configmap', 'configmap_yaml')
k8s_yaml('kafka-consumer-app/yaml/ns.yaml')

k8s_yaml(configmap_yaml('kafka-policy', namespace='kafka', from_file=['./envoy-kafka/policies/allow_all.rego']))
k8s_yaml(configmap_yaml('kafka-proxy-config', namespace='kafka', from_file=['./envoy-kafka/envoy.yaml']))
k8s_yaml([
  './envoy-kafka/deployment.yaml',
  './envoy-kafka/service.yaml'])

k8s_yaml(configmap_yaml('app-policy', namespace='kafkaconsumer', from_file=['./kafka-consumer-app/policies/allow_all.rego']))
k8s_yaml(configmap_yaml('proxy-config', namespace='kafkaconsumer', from_file=['./kafka-consumer-app/config/envoy.yaml']))
k8s_yaml(['kafka-consumer-app/yaml/deployment.yaml','kafka-consumer-app/yaml/service.yaml'])
watch_file('kafka-consumer-app/config')



custom_build(
  'kafkaapp',
  'demo/backend/spring-kafka/build_docker.sh $EXPECTED_REF',
  ['./demo/backend/spring-kafka/kafkaapp'],
  skips_local_docker=True,disable_push=True
)

k8s_resource('example-app', port_forwards='8080:8000')

local_resource('attestation', cmd='scripts/attestation.sh',resource_deps=['spire-server'])


