name: test-service
trustDomain: example.org
kafkaClusters:
  test-cluster:
    bootstrapPort: 9100
    brokers:
      kafka0:
        listenPort: 9101
        brokerAddress: kafka-cp-kafka
        brokerPort: 9093
