name: kafkaconsumer
spiffeId: spiffe://example.org/ns/kafkaconsumer/sa/default
trustDomain: example.org
kafkaClusters:
  test-cluster:
    bootstrapPort: 9100
    spiffeId: spiffe://example.org/ns/default/sa/default
    brokers:
      kafka0:
        listenPort: 9101
        brokerAddress: kafka-cp-kafka
        brokerPort: 9093
