name: test-service
trustDomain: testing.internal
kafkaClusters:
  test-cluster:
    bootstrapPort: 9100
    brokers:
      kafka0:
        listenPort: 9101
        brokerAddress: kafka0.internal
        brokerPort: 9093
