apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sslfactory
  name: sslfactory
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: sslfactory
  type: NodePort
status:
  loadBalancer: {}